from pathlib import Path
import json,datetime,shutil,hashlib
P=Path(__file__).parent;old=P.parent/'R21_PCB_V3V3_MINIMAL_CONNECTION_CORRECTION_V1'
now=datetime.datetime.now(datetime.timezone.utc)
b={'package':'SCIENCE_ADK5556_4X4_R21_PCB_LOCAL_POUR_CLEARANCE_AND_FINAL_WARM_COLD_V1','rulingAssistant':'dd5c432a-162f-4a19-9719-a8575b3ee300','parentUser':'52b37bbe-46e5-4a7f-8af9-89ec3d99e284','startUTC':now.isoformat(),'approvedMinutes':120,'status':'ACTIVE','limits':{'copy':1,'session':2,'save':1,'captureaudit':3,'DRC':3,'reviewExport':1,'normalPourUpdate':1},'actual':{'copy':0,'session':0,'save':0,'captureaudit':0,'DRC':0,'reviewExport':0,'normalPourUpdate':0},'reservations':[],'newLINE':0,'newVIA':0,'deleteLINEVIA':0,'componentMove':0,'netValueFootprintRule':0,'schematic':0,'ImportChanges':0,'autorouter':0,'simulation':0,'Gerber':0,'procurement':0,'manufacture':0,'actualBench':0,'localGit':0,'system':0}
assert not(P/'EXECUTION_BUDGET.json').exists();(P/'EXECUTION_BUDGET.json').write_text(json.dumps(b,indent=2),'utf8')
for n in('cli_call.py','reserve.py','capture_routing.js','drc_routing.js','save_only.js'):shutil.copyfile(old/n,P/n)
src=old/'SCIENCE_ADK5556_4X4_R21_V3V3_MINIMAL_WORK.eprj2';dest=P/'SCIENCE_ADK5556_4X4_R21_POUR_CLOSURE_WORK.eprj2';b['actual']['copy']=1;b['reservations'].append({'utc':now.isoformat(),'kind':'copy','count':1,'reason':'One isolated copy of actual14 work; entry gate must verify all14 V3V3 IDs before any pour update.'});(P/'EXECUTION_BUDGET.json').write_text(json.dumps(b,indent=2),'utf8');assert not dest.exists();shutil.copyfile(src,dest);sha=hashlib.sha256(src.read_bytes()).hexdigest().upper();assert hashlib.sha256(dest.read_bytes()).hexdigest().upper()==sha
(P/'INPUT_COPY_HASH.json').write_text(json.dumps({'source':str(src),'copy':str(dest),'bytes':src.stat().st_size,'SHA256':sha,'identical':True,'inputQualification':'Unqualified until actual entry capture confirms14 approved copper and176/550/514/107/36'},indent=2),'utf8')
(P/'IMPLEMENTATION_PLAN.md').write_text('# Ruling15: one normal pour update and final warm/cold\n\nOne isolated copy, correct GUI PCB1 ready, entry capture1 must contain all14 approved LINE/VIA and original550/176 identities/rules. Missing copper: STOP, never redraw.\nThen one native Rebuild All, immediate detailedDRC. Any real error STOP, no secondpour/edit. All0 permits unique save, warm capture2, normalclose; independentcold GUI-ready, capture3 andDRC. All550/176 and nonderived copper frozen; POURED derived allowed only,4POUR boundaries/nets/priorities/rules unchanged. Historicaltwo0.1mil LINE representation is accepted, no rebuild/remove/research.\nReview only, no manufacture/bench. Complete/blocked receipt plus one fresh-context whole-package review, immutable GitHub directory, one handoff and successor replymonitor.\n','utf8')
print(json.dumps({'copyBytes':dest.stat().st_size,'SHA256':sha,'startUTC':b['startUTC']}))
