from pathlib import Path
import json,datetime,csv,hashlib,math
p=Path(__file__).parent;b=json.loads((p/'EXECUTION_BUDGET.json').read_text(encoding='utf-8'));assert not b['STOP'] and b['spent']['OP_AC_PZ']+4<=8
b['spent']['OP_AC_PZ']+=4;b['events'].append({'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'cost':{'OP_AC_PZ':4},'purpose':'Conservative precharge4 scalar analytic DC endpoints; actualSPICE0, no transient models','prechargedBeforeCalculation':True});(p/'EXECUTION_BUDGET.json').write_text(json.dumps(b,indent=2),encoding='utf-8')
top=16900;bot=10000;lo=1.15*.99*(1+top*.999/(bot*1.001))-1e-7*top*1.001;hi=1.15*1.01*(1+top*1.001/(bot*.999))+1e-7*top*1.001
offupper=6*3.6/(4990*.999/101+6);offideal=6*3.6/(4990*.999*(2/101)+6)
rs=[{'endpoint':'U12_falling_low','V':lo},{'endpoint':'U12_falling_high','V':hi},{'endpoint':'OFF_nonconducting_added_diode_upper','V':offupper},{'endpoint':'OFF_zeroVF_equal_rail_conditional_limit','V':offideal}]
with(p/'C101_ANALYTIC_STATIC_ENDPOINTS.csv').open('w',encoding='utf-8',newline='')as f:w=csv.DictWriter(f,fieldnames=['endpoint','V']);w.writeheader();w.writerows(rs)
(p/'C101_STATIC_ASSUMPTIONS.md').write_text('''# Fresh analytic bounds for the actual101candidate — NOT SPICE/bench
4scalarDCendpoints conservatively charged to8-analysis allowance; actualSPICE/TRAN0. U12 uses actual16.9k±.1%/10k±.1%, TPS3890 reference1.15V±1%, leak±.1uA; no separate temperature-drift envelope or waveform proof. Nominal3.0935V. Do not use old16.99-chain bounds as current result.
New topology explicitly includes diode2(A)=V3V3→1(C)=V5,100R bleeds onbothrails, U9 reverse-blocking inputcontract. Under boardOFF, sixpositiveexternal sources≤3.6V, six4.99k−.1%, bleeds+1%=101R, no externallypoweredJ2/NRSTpushpullhigh: KCL6(Vext−V3)/Rs=V3/R3+I_D+I_load. For forwardDcurrent≥0/nootherenergy source, nonconducting upper boundV3≤.390197835V. IdealzeroVF equalrails plusbothbleeds gives.206277209V, merely a conditional lower-loss example, not a guaranteed voltage or diodeVF model. Added Schottky creates a discharge/bypass path, NOT reverse isolation. Real OFF/clamp/leak/negativefault/temperature/fastEN/muxlatency H0LD. The arbitraryexternal≤3.6V ceiling is an analytic assumption, not a newlyapproveduniversalinterface contract.
NominalVEX16.2k×100n=1.62ms; approvedfirstMEASURE≥10msafterV5/VCMestablished is a firmwarecontract, not flashed/benchverified. LDOdiode1A/VF450mV at25C/IFSM50A8.3msratings are conditional datasheetvalues; actual peak/wiringESR/Ceff/thermal/pulse shape not modeled. No fake waveform or suddenVINremovalPASS. No fullmatrix/PZretry.
''',encoding='utf-8')
old=json.loads((p/'BASELINE_C_ACTUAL_PARTS_AND_NETS.json').read_text(encoding='utf-8'));new=json.loads((p/'FINAL_COLD_CAPTURE_ACTUAL_PARTS_AND_NETS.json').read_text(encoding='utf-8'));op={q['ref']:q for pg in old['pages']for q in pg['parts']};np={q['ref']:q for pg in new['pages']for q in pg['parts']};allowed={'U12_TOP0','D_FFC_ROW','D_FFC_COL'};removed=set(op)-set(np);added=set(np)-set(op);unchanged=[];errors=[]
for ref in set(op)&set(np)-allowed:
 a=op[ref];z=np[ref];fields=['id','ref','type','name','sub','association','footprint','props','pins']
 if any(a[k]!=z[k]for k in fields):errors.append(ref)
 else:unchanged.append(ref)
assert removed=={'U12_TOP1','U12_TOP2','U12_TOP3'}|{prefix+str(i)for prefix in ['R_COL_SENSE','R_TIA_ISO','C_TIA_HF']for i in range(4)} and added=={'D_LDO_REV'} and not errors
(p/'PERMITTED_DIFF_AND_97_UNCHANGED.json').write_text(json.dumps({'removed':sorted(removed),'added':sorted(added),'3ExistingUpdated':sorted(allowed),'97OtherPartsCoreCoordsPinsPropsFootprintStrictlyUnchanged':len(unchanged),'unexpectedDifferences':errors},indent=2),encoding='utf-8')
diff=[]
for ref in sorted(set(op)|set(np)):
 o=op.get(ref);n=np.get(ref)
 diff.append({'ref':ref,'action':'REMOVED'if n is None else'ADDED'if o is None else'APPROVED_UPDATE'if ref in allowed else'UNCHANGED','oldName':o['name']if o else'','actualName':n['name']if n else''})
with(p/'C101_DESIGNATOR_DIFF.csv').open('w',encoding='utf-8',newline='')as f:w=csv.DictWriter(f,fieldnames=list(diff[0]));w.writeheader();w.writerows(diff)
g={'C_ELECTRICAL_EDITS_COMPLETE':True,'C101_ACTUAL_BOM_PIN_NET_PASS':True,'COLD_REOPEN_SEMANTIC_PASS':True,'TPD_COMPONENT_MAKER_MPN_CORRECTED':True,'C_SCHEMATIC_ACCEPTED':False,'PCB_PLACEMENT_ELIGIBLE':False,'SYSTEM_PERFORMANCE_ACCEPTED':False,'PCB_ROUTING_RELEASED':False,'BENCH_RELEASED':False,'MANUFACTURE_RELEASED':False,'ERC_DETAIL_HOLD':True,'LEGACY_ANNOTATION_HOLD':True,'DRAWING_STANDALONE_RELEASE':False,'FULL_MATRIX_DYNAMIC_PERFORMANCE_HOLD':True,'MLCC_CEFF_HOLD':True,'FFC_MECHANICAL_HOLD':True,'DNPRecoveryFalsePlaceholderRemoved':True,'STOP':'C101_NATIVE_EDITS_AND_COLD_COMPLETE_ERC_DETAIL_AND_LEGACY_DRAWING_HOLD_HARD_QUOTAS_USED'}
(p/'GATES.json').write_text(json.dumps(g,indent=2),encoding='utf-8');b['STOP']=True;b['STOPUTC']=datetime.datetime.now(datetime.timezone.utc).isoformat();b['STOPReason']=g['STOP'];b['actualSPICEProcesses']=0;b['actualSaveInterfaceAttempts']=4;b['saveReservationContinuedAfterPreSaveGuardFailure']=True;b['nativeColdCompleted']=True;b['analyticScalarEndpoints']=4;(p/'EXECUTION_BUDGET.json').write_text(json.dumps(b,indent=2),encoding='utf-8')
(p/'DRAWING_ANNOTATION_ADDENDUM.md').write_text('''# MandatoryC101drawing companion — nativePDFaloneNOTRELEASED
SixactualcoldPDFpages viewed. Components/netlabels are zoom-readable, but sparsegrids/tightmargins and oldR2 notes/title persist aftercoldimport, contrary to previousC103warmPDFclearedview. ActualC101electricalsource/363pinCSV is authoritative; no additionalnative save/PDF or investigation.
Page1: U8 is TPS7A3701, notoldTPS7A20; singleREF3025 drivesVCM/divider; newPMEG2010BER1C=V5,2A=V3V3. R2title/feedback/1ksense wording is historical.
Page2: current singleOPA388+dual4:1TMUX1109, activehighROW_MUX_EN fromMCU with100k pulldown, notold MCU_ROW_AND_HW_ENABLE four-rowANDlogic. OldSchmitt/HW_ENABLE descriptions and ideal300usPASS are invalidcurrenthardwareclaims.
Page3: currentdirectTIA: COLx→OPAminus, RF||CF betweenCOLx andTIAx, outputTIAx→100R→ADCinput with10nFGND. OldCOL10k/isolated1k wording is NOT current. All12NC DNP removed. Recovery ONLY byfutureexplicit boundedECO restoringfulloldremote-sensetopology; no solderablefakeDNP.
Page4: ADCbulk retained, Ceffunverified; note count44u nominalnotactualeffectivecapacitance. ADCinternalreference onlyifenabled, dynamic/noise100fpsunverified.
Page5: MCU pin16 nowROW_MUX_EN; noU13/U14/U15 orSchmittAND inC. Six4.99k paths/NRST1k remain, NRSTexternalODHiZonly. Old48kframe/MCU_ENABLE/Schmitttextnotcurrentfwproof.
Page6: U11 separatePWR5_OK withdiodepropagation toPGOOD, U12single16.9k/10k nominal3.0935V; oldPGOODcommonbothwiredoutputs/3.1085V/twoLM73100 notesincorrect. Newpowersequenceacceptedcandidate, not benchfaultPASS. InitialMEASURE>=10msafterV5/VCMestablished pernewruling.
Therefore standalonePDFfunctional-annotationgate NOTmet. PreserveoldtitleactualPDFevidence, doNOTrenameitaccepted final. Full97unchangedcomponentaudit andwarm/cold363pin/netactualmaps supplied. This documentationcompaniondoesnotpretendnativeTextupdated; Procanacceptpairedrevieworidentifyoneboundedactualremainingrequirement, noAPIresearchloop.
''',encoding='utf-8')
(p/'PRIMARY_SOURCE_NOTES.md').write_text('''# Two new primary sources
NexperiaPMEG2010BER2023p1–2/5: https://assets.nexperia.com/documents/data-sheet/PMEG2010BER.pdf ; pin1K/cathode,2A/anode, SOD123W, IFAV1A, VFmax450mV@1A25C, IFSM50A8.3mshalf-sine25C. Those do notprove actualpulse/temperature orlayout. ChosenactualNexperiaPMEG2010BER,115 catalog, notMSKSEMIclone. ActualfootprintnameSOD123_L2.8-W1.8/SupplierFootprintSOD123W; PCBland/mechanicalqualificationnotperformed.
ExactYageoRT0603BRD0716K9Lofficial1page: https://yageogroup.com/component-documentation/download/specsheet/RT0603BRD0716K9L ;16.9k±.1%,±25ppm/C,0603. InitialoldYageoPDFaliasopeninternalerror/irrelevantsearch retained as failedlookup, laterexactofficialspecsheetverified; uniqueRTmaterialsource countedonce, notinventedfetchsuccess. Noadditionalmaterialcandidates orsourcebulkpublic.
TPD/TPS7A37/TPS3890/BAT/MCUprimarydatasheets alreadyqualifiedinpriorpackage/ruling, notnew sources. ActualTPDcomponentattrs ManufacturerTI/ManufacturerPart/MPNcorrectcold; notglobalstock/lotauthenticity orPCBfootprintPASS.
''',encoding='utf-8')
receipt='''# C101 nativefinal closeout — electricaledits/coldPASS, formalacceptanceHOLD
Fullrulinge296d002/parent8d08e41a saved. Unique240minscope fullyimplemented prescribednativeedits, no architecturechange/PCB/solverresearch. Current101isactual, nottargetestimate. Fourchanges: newPMEG2010BEROUT→IN; U12fourtopR→singleaccurate16.9k; delete12NC DNP; correcttwoTPDmaker/MPN. VEX18/162/allADCbulks/other97parts strictunchanged.

## Actual evidence
101structural/populated, rawnativeBOMflags101yes0no,0DNP:36R44C7protection10IC4J.363pins323connected54nets40NC; actualwarm/cold363/363bothcandidateplanmatches. Full101componentidentity/core/name/value/coordinates/pinsets/materialattrs/footprintsandallnetmap warm=cold. Raw125387byteFiles have differentSHA butsamefullrawlinemultiset; property/orderrepresentation difference, nothiddenelectricaldelta. Eachsha retained. Exact97unchangedparts/15removedrefs/oneaddedD/threeupdatedexisting shown inPERMITTED_DIFF_AND_97_UNCHANGED.json andCSV; noothernet/part/value/schema changes.
ActualD_LDO_REV1=C/cathode→V5,2=A/anode→V3V3, sourceNexperiaPMEG2010BER,115. ActualU12_TOP0 RT0603BRD0716K9L, twoownedports/wires new and8oldports/wires removed byexactsourceownership, no broadnetdeletion; nointermediateU12DIVnetsleft. ActualcoldTPDattrsTI/ManufacturerPart/MPN allcorrect. Wholeprojectexportincludesold176PCBNOTCPCB. Workingcopy/rawnativeprivacylocalonly; publicmetadata-strippedderivative separatelyhashed/unreopened, nativecold proof appliesprivatecopy, notderivativecoldopen.
Nativewarmfirstsessionclosedbeforesecondcoldopen; coldread/export/sessionofficialclosed. OldC103sourceSHA6D68615A1BD545EFB674718A61BA5CE5ACF432E326E22C80F93A5A5A3E2E217Dunchanged. No otheruserGUI/session interrupted, no solverlaunched.

## Actual partial failures, never erased
CopyimportsnewprojectUUID; tworeadcommandsguardedwitholdUUIDfailedbeforeaction, failedcapture1/audit1charged; exactfilename/projectidentifiednormally andguardupdated. NewdiodecreatedonceunsavedthenoverstrictpolarityguardrejectedactualCathodeC (expectedK/Cathode). Narrowreadproved1C2A vsmanufacturerdatasheet1K2A; realunitRED→3GREENincludingreversalrejection. Firstplannedpowersavewasprecharged1butsaveinterfaceNOTreached; sameexistingdiodecontinued(no recreate/refund), sameoneoutstandingreservationcoversoneactualpowersave. Otherthreepagesprecharge1each;actualsaveinterfaceattempts4/4alltrue. This is NOT fiveactualsaves or claimingattemptrefund. Initialfailedinvoke/logs/codepreserved. LocalownedsourceparserfirstfailedonemptyENDrecord; correctedskipno-bodyEND, noCADreplay/sourcealteration.

## Remaining formal closing gates
SingleERCreturns[{type:warn,count:752}], no detailedwarningbody. Old772→752iscountonly; cannotprovezero newCritical/Important orERCdetailPASS. ERC_DETAIL_HOLD.
SixactualcoldPDFpagesexported/rendered/viewed. Maincomponents/netlabelszoom-readable, butoldR2notesreturned/persisted atcold, includingincorrectoldROWAND/Schmitt/fullremoteTIAs/twoLM73100/resetthreshold. This contradictsnewC101topology; mandatoryDRAWING_ANNOTATION_ADDENDUM.mdandactual363CSV provided. Nofalseclaim nativeText updated orstandalonefinalPDF. Sparsegrid/smalltext/toptightmargin remain; noquota toedit/renderanewnativePDF.
These two evidence/documentgates blocklocallyclaiming C_SCHEMATIC_ACCEPTED/PCB_PLACEMENT_ELIGIBLE. Electricaleditsandcoldarecompleted, notneedanotherfullarchitecture/SPICEproof. Fullmatrix NUMERICAL_UNRESOLVED/PZ_INVALID_PORT_SETUP andsystemprecision/noise100fps/FFCmechanical/Ceff/benchholdsretained perPro; they doNOTreopenoldsolverwork.
Fresh4conditionalanalyticalDCendpoints accountnewdiode/tworailbleedKCLandactual16.9kthreshold. OFFworstnonconducting≤.3902V,idealzeroVF/twoloadexample~.2063V underexplicit≤3.6V external/noNRSTpushpullhigh/noactiveJ2 assumptions. No blanketreverseblocking/pulse/dynamicfaultPASS;diodebypassesOUT→INand canenergizelocalV5whileU9inputisolated. Valuesareconditional, notSPICE orbenchtrace; OPAC/PZ4/8chargedanalytic, actualSPICE/TRAN0.

## STOP/budget/finalreview/delivery
copy1/session2/save4/capture3/audit3/ERC1/PDF1limitsfull (failedpre-readcapture/audit included),source2/powercandidate1; noextraactivenativepending. STOP=C101_NATIVE_EDITS_AND_COLD_COMPLETE_ERC_DETAIL_AND_LEGACY_DRAWING_HOLD_HARD_QUOTAS_USED. AllfutureCAD/SPICE/parameter/placement/PCB prohibiteduntilfullnewunifiedscope. PCB/routing/pour/Gerber/manufacture/procurement/bench/localGit/system0. Remaininganalysis/time notauthorizationtofixnotes/ERCtools.
Onefresh-context finalreviewandonealloweddoc/disclosurepass only; nobudgetcarry/secondreview. Completepublicowncode/actualpinBOMdiff/cold/net/6PDFPNGs/sanitizednative/SCH/failedCLIevidence directfileattachments+manifest/ZIP fixedGitHubversion. RawaccountSQLite/rawnativeauthorcontext/thirdpartybulk excludedwithhashreason. Rulings/costsinPLAN_AND_LEDGER. Solepairnew6abfe3f5; neverold69ddread/send. One normalshortreport, owner+nextCheck+successormonitor same turn; nosendblindretry.
END-OF-COMPLETE-C101-NATIVE-FINAL-CLOSEOUT-ERC-DRAWING-HOLD-RECEIPT
'''
(p/'COMPLETE_C101_FINAL_RECEIPT.md').write_text(receipt,encoding='utf-8');(p/'README.md').write_text(receipt,encoding='utf-8');print(json.dumps({'actual101':True,'97unchanged':len(unchanged),'fourAnalyticEndpoints':rs,'STOP':b['STOP']}))
