from pathlib import Path
import json
p=Path(__file__).parent
base=json.loads((p/'BASELINE_C_NATIVE_BUILD_PLAN.json').read_text(encoding='utf-8'));v=json.loads((p/'FINAL_MATERIAL_IDENTITY_CONFIRMED.json').read_text(encoding='utf-8'))['parsed']['value']
diode=next(x for x in v['searches']['PMEG2010BER']if x['manufacturerId']=='PMEG2010BER,115');res=next(x for x in v['searches']['RT0603BRD0716K9L']if x['manufacturerId']=='RT0603BRD0716K9L')
assert len(diode['uuid'])==len(res['uuid'])==32
base['project']=v['project']['uuid'];parts=[q for q in base['parts']if not q['dnp'] and q['ref']not in ['U12_TOP1','U12_TOP2','U12_TOP3']]
for q in parts:
 if q['ref']=='U12_TOP0':q.update(association={'libraryUuid':res['libraryUuid'],'uuid':res['uuid']},sub=res['symbolName']+'.1',name=res['manufacturerId'],value='16.9k 0.1% 25ppm',nets={'1':'V3V3','2':'U12_DIV0'},role='Single exact16K9 top; nominalTPS3890 threshold3.0935V')
 if q['ref']in ['D_FFC_ROW','D_FFC_COL']:q['role']='Texas Instruments TPD4E05U06DQAR;J2 passive-only ESD, not continuous DC fault protection';q['manufacturer']='Texas Instruments';q['MPN']='TPD4E05U06DQAR'
parts.append({'ref':'D_LDO_REV','page':0,'association':{'libraryUuid':diode['libraryUuid'],'uuid':diode['uuid']},'sub':diode['symbolName']+'.1','name':'PMEG2010BER,115','value':'PMEG2010BER','nets':{'1':'V5','2':'V3V3'},'dnp':False,'role':'Anode2V3V3 to Cathode1V5;LDO reverse-current bypass, notreverse-blocking','manufacturer':'Nexperia','MPN':'PMEG2010BER,115'})
# Original U12 chain endpoint U12_SENSE is pin2 of TOP3: single top must go there.
u=next(q for q in parts if q['ref']=='U12');top=next(q for q in parts if q['ref']=='U12_TOP0');top['nets']['2']=u['nets']['1']
base['parts']=parts;base['populatedCount']=base['structuralCount']=101;base['hold']=['SYSTEM_PERFORMANCE_HOLD','FFC_MECHANICAL_HOLD','MLCC_CEFF_HOLD','BENCH_NOT_RELEASED'];(p/'FINAL_BUILD_PLAN.json').write_text(json.dumps(base,ensure_ascii=False,indent=2),encoding='utf-8')
common="""const project=await eda.dmt_Project.getCurrentProjectInfo();if(project.uuid!==PROJECT)throw Error('Wrong final copy');async function find(ref){const cs=(await eda.sch_PrimitiveComponent.getAll()).filter(c=>c.getState_ComponentType()==='part'&&c.getState_Designator()===ref);if(cs.length!==1)throw Error('Wrong ref '+ref);return cs[0];}async function create(q,x,y){const c=await eda.sch_PrimitiveComponent.create(q.association,x,y,q.sub,0,false,true,true);if(!c)throw Error('create '+q.ref);const m=await eda.sch_PrimitiveComponent.modify(c.getState_PrimitiveId(),{designator:q.ref,name:q.value,otherProperty:{...c.getState_OtherProperty(),Value:q.value,'Add into BOM':'yes',DNP:'no',Manufacturer:q.manufacturer||'YAGEO',MPN:q.MPN||q.name,'Review Status':'C final candidate / noPCBbenchrelease','Circuit Role':q.role}});if(!m)throw Error('modify '+q.ref);const pins=await eda.sch_PrimitiveComponent.getAllPinsByPrimitiveId(m.getState_PrimitiveId());if(pins.length!==Object.keys(q.nets).length||pins.some(z=>!(String(z.getState_PinNumber())in q.nets)))throw Error('Pinset '+q.ref);const result=[];for(const z of pins){const num=String(z.getState_PinNumber()),name=z.getState_PinName();if(q.ref==='D_LDO_REV'&&!((num==='1'&&/K|Cathode/i.test(name))||(num==='2'&&/A|Anode/i.test(name))))throw Error('Diode actualpolarity');await z.setState_NoConnected(false).done();const delta={0:[120,0],180:[-120,0],90:[0,120],270:[0,-120]}[z.getState_Rotation()];if(!delta)throw Error('Pinrotation');const port=await eda.sch_PrimitiveComponent.createNetPort('BI',q.nets[num],z.getState_X()+delta[0],z.getState_Y()+delta[1],z.getState_Rotation(),false);if(!port)throw Error('port');const a=await eda.sch_PrimitiveComponent.getAllPinsByPrimitiveId(port.getState_PrimitiveId());const w=await eda.sch_PrimitiveWire.create([[z.getState_X(),z.getState_Y(),a[0].getState_X(),a[0].getState_Y()]],q.nets[num]);if(!w)throw Error('wire');result.push({num,name,net:q.nets[num]});}return{ref:q.ref,pins:result};}\n""".replace('PROJECT',json.dumps(base['project']))
script0=common+"await eda.dmt_EditorControl.openDocument('595d5f2f11dee03d');const added=await create(DIODE,2070,120);const saved=await eda.sch_Document.save();if(saved!==true)throw Error('save');return{added,saved};".replace('DIODE',json.dumps(parts[-1],ensure_ascii=False))
(p/'final_edit_power.js').write_text(script0,encoding='utf-8')
script1=common+"await eda.dmt_EditorControl.openDocument('802bf258e0d38cab');const out=[];for(const ref of ['D_FFC_ROW','D_FFC_COL']){const c=await find(ref);const m=await eda.sch_PrimitiveComponent.modify(c.getState_PrimitiveId(),{otherProperty:{...c.getState_OtherProperty(),Manufacturer:'Texas Instruments',MPN:'TPD4E05U06DQAR','Manufacturer Part':'TPD4E05U06DQAR','Circuit Role':'J2 passive-only ESD, notcontinuousDCfault','Review Status':'C final candidate / noPCBbenchrelease'}});if(!m)throw Error('TPDmodify');out.push({ref,props:m.getState_OtherProperty()});}const saved=await eda.sch_Document.save();if(saved!==true)throw Error('save');return{out,saved};"
(p/'final_edit_tpd.js').write_text(script1,encoding='utf-8')
script2=common+"await eda.dmt_EditorControl.openDocument('49bb518d907ff185');const removed=[];for(let i=0;i<4;i++)for(const prefix of ['R_COL_SENSE','R_TIA_ISO','C_TIA_HF']){const ref=prefix+i;const c=await find(ref);const ps=await eda.sch_PrimitiveComponent.getAllPinsByPrimitiveId(c.getState_PrimitiveId());if(ps.some(z=>!z.getState_NoConnected()))throw Error('DNPnotNC');if(!await eda.sch_PrimitiveComponent.delete(c))throw Error('delete');removed.push(ref);}const saved=await eda.sch_Document.save();if(saved!==true)throw Error('save');return{removed,saved};"
(p/'final_edit_dnp.js').write_text(script2,encoding='utf-8')
# Delete only the four top resistors and their owned net-port/wire entities by exact baseline pin coordinates; no global net deletion.
actual=json.loads((p/'BASELINE_C_ACTUAL_PARTS_AND_NETS.json').read_text(encoding='utf-8'));chain=[q for pg in actual['pages']for q in pg['parts']if q['ref']in ['U12_TOP0','U12_TOP1','U12_TOP2','U12_TOP3']]
script5=common+"await eda.dmt_EditorControl.openDocument('cae95ff24beaad15');const old=CHAIN;const points=old.flatMap(q=>q.pins.map(z=>[z.x,z.y]));const ownedPorts=[];for(const w of await eda.sch_PrimitiveWire.getAll()){const a=w.getState_Line();if(a.some?false:false){} }return {status:'READONLY_WIRE_OWNERSHIP_REQUIRED',chain:old};".replace('CHAIN',json.dumps(chain))
(p/'U12_CHAIN_BASELINE.json').write_text(json.dumps(chain,indent=2),encoding='utf-8')
print(json.dumps({'target101':len(parts),'project':base['project'],'diode':diode['manufacturerId'],'U12SingleBottomNet':top['nets']['2'],'pendingOnlyExactU12WireOwnership':True}))
