from pathlib import Path
import json
P=Path(__file__).parent;plan=json.loads((P/'TWO_LOCAL_BRIDGES_PLAN.json').read_text('utf8'))
assert len(plan['bridges'])==2 and len(plan['newVias'])==1
assert all(not q['geometricScreenOtherNetClearanceBelow6Mil']for q in plan['bridges'])and not plan['newVias'][0]['geometricOtherNetClearanceBelow6Mil']
segs=[{'net':'V3V3','layer':q['layer'],'width':12,'x1':a[0],'y1':a[1],'x2':b[0],'y2':b[1]}for q in plan['bridges']for a,b in zip(q['points'],q['points'][1:])]
guard="const pr=await eda.dmt_Project.getCurrentProjectInfo();if(pr.uuid!=='6c25a449ce9ab470f4c1db4bd85120e6cad325b0f291f573b07c6aaa4d353ee1')throw Error('Wrong isolated copy');await eda.dmt_EditorControl.openDocument('268e6597399ebcce');"
code=guard+"const src=await eda.sys_FileManager.getDocumentSource();const rs=src.split('\\n').filter(x=>x.includes('||')).map(x=>{const z=x.split('||');return [JSON.parse(z[0]),JSON.parse(z[1].replace(/\\|+$/,''))];});const old=rs.find(([h,b])=>h.type==='LINE'&&h.id==='c131c12ef419b393');if(!old||old[1].netName!=='V3V3'||old[1].layerId!==1||old[1].startX!==3200.8||old[1].endX!==3160.05)throw Error('Local replacement guard');const removed=await eda.pcb_PrimitiveLine.delete('c131c12ef419b393');if(!removed)throw Error('Local line delete failed');const created=[];const nv="+json.dumps(plan['newVias'][0])+";const via=await eda.pcb_PrimitiveVia.create(nv.net,nv.x,nv.y,nv.hole,nv.diameter);if(!via)throw Error('One local via failed');created.push({type:'VIA',id:via.getState_PrimitiveId()});const ss="+json.dumps(segs)+";for(const s of ss){const t=await eda.pcb_PrimitiveLine.create(s.net,s.layer,s.x1,s.y1,s.x2,s.y2,s.width,true);if(!t)throw Error('Local bridge line failed');created.push({type:'LINE',id:t.getState_PrimitiveId()});}return {removed:'c131c12ef419b393',created,saveCalled:false,pourRebuildCalled:false};"
(P/'apply_two_local_bridges.js').write_text(code,'utf8');(P/'save_only.js').write_text(guard+"return {saved:await eda.pcb_Document.save()};",'utf8');print(json.dumps({'createdLINE':len(segs),'deletedLINE':1,'newVia':1,'save':False,'explicitPourRebuild':False}))
