from pathlib import Path
import json,hashlib,datetime,csv,os
from science import ROOT,OLD,dump,sha
now=datetime.datetime.now(datetime.timezone.utc).isoformat();b=json.loads((ROOT/'EXECUTION_BUDGET.json').read_text());b['scienceStopped']=True;b['stopUTC']=now;b['stopReason']='Binding MIMO sigma_min<0.20 technical review; low-frequency matrix reconstruction/reference normalization not qualified; not a physical instability finding';dump(ROOT/'EXECUTION_BUDGET.json',b)
g={'RETURN_RATIO_METHOD_VALIDATED':'PASS_ACCEPTED_PRIOR','FAULT_LATENCY_LOGIC_CONTRACT_PASS':'PASS_ACCEPTED_OFFLINE_PRIOR','RESET_DIRECT_PATH_25C_DESIGN_PASS':'PASS_ACCEPTED_PRIOR','RESET_20_30C_BENCH_HOLD':True,'FAULT_PROTECTION_HOLD':True,'MIMO_STATIC_COUPLED_SCREEN_PASS':'HOLD_TECHNICAL_REVIEW','PARTITIONED_COUPLED_DYNAMIC_PASS':'HOLD_NO_SHORT_TRANSIENT_RUN_AFTER_MIMO_REVIEW_GATE','PZ':'TOOL_OR_MODEL_PORT_CHAIN_CAPABILITY_LIMIT_NOT_HARD_GATE','P3':'NOT_ENTERED','BENCH_PCB_MANUFACTURE':'NOT_RELEASED'};dump(ROOT/'GATES.json',g)
rows=[]
for case in b['cases']:
    p=ROOT/'results'/case['name'];st=json.loads((p/'STATUS.json').read_text());assert st['status']!='RUNNING'
    err=(p/'stderr.log').read_text(errors='replace');rows.append({'case':case['name'],'phase':case['phase'],'charges':'+'.join(case['charges']),'status':st['status'],'analysisStatus':st.get('analysisStatus'),'seconds':st.get('wallSeconds'),'ownedPID':st.get('ownedPID'),'rawOP':(p/'op.raw').exists(),'AC':(p/'ac.txt').exists(),'hybridAC':(p/'hybrid.txt').exists(),'PZactualPlot':(p/'pz.raw').exists() and 'Plotname: Pole-Zero Analysis' in (p/'pz.raw').read_text(errors='replace'),'firstError':next((line for line in err.splitlines() if 'Error' in line or 'doAnalyses:' in line),'')})
with (ROOT/'CASE_EXECUTION_INDEX.csv').open('w',newline='',encoding='utf-8-sig') as f:w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
for n in ['protocol.py','progress_protocol.py','test_protocol.py','test_progress.py']:
    (ROOT/n).write_bytes((OLD/n).read_bytes())
dump(ROOT/'evidence/PROTOCOL_FROZEN_SHA.json',{n:sha(ROOT/n) for n in ['protocol.py','progress_protocol.py','test_protocol.py','test_progress.py']})
(ROOT/'FIRMWARE_INTERFACE_CONTRACT.md').write_text('''# Frozen accepted progress watchdog interface\n\nNo second state machine or code change. The four Python files are byte-identical to approveda3e22772 inputs;32 finalGREEN tests accepted by Pro, no new regression claimed in this package.\n\nActive-low OD/OC NRST,Hi-Z release,VOL<=0.4V. Direct1k reset25C design accepted;20-30C/temperature and±5V fault/thermal/backfeed remainbench/faultHOLD. No new clamp selected because the MIMO scientificSTOP was reached beforeP2.\n\nEight alternatingblank/row states;288 transfers,32dummy,256 valid perframe; heartbeat1ms carryingepoch/frame/state0..7/last-valid-sample completion time/count. Heartbeat4.5ms/progress2.5ms timeout, no-progress repeats do notrefreshdeadline; receive tick<=1ms, qualified capture-to-receive/timebase conversion<=.5ms are firmware obligations. PGOOD and tags/ranges immediately invalidate; clear preserves replay/clock watermarks; failedreset/config immediatelyclear; two genuinely new completeframes recover. RealMCU/UART/SPI/WCET and100fps stillpendingbench.\n''',encoding='utf-8')
print(json.dumps({'cases':len(rows),'used':b['used'],'scienceStopped':True,'allStatusesTerminal':True,'nativeOperations':0}))
