const expected='f584056ea8f7cc74a210f932891fde19f1d1518be7e7f4466d0c7acd11c29efe';
const p=await eda.dmt_Project.getCurrentProjectInfo();if(p?.uuid!==expected)throw Error('Wrong R2 project');
const names=['Power_Reference','Rows_8lead_Interface','Continuous_Column_TIAs','ADS8684_Decoupling','MCU_Protected_Interfaces','Power_Qualification'];
let schematics=await eda.dmt_Schematic.getAllSchematicsInfo();if(schematics.length!==1||schematics[0].uuid!=='32047f874e6d71ce')throw Error('Unexpected initialized R2 schematic');
const id=schematics[0].uuid;
const info=await eda.dmt_Schematic.getSchematicInfo(id);const ids=(info?.page||[]).map(x=>x.uuid);
if(ids.length>1)throw Error('Unexpected initial pages');
while(ids.length<6){const page=await eda.dmt_Schematic.createSchematicPage(id);if(!page)throw Error('Page creation failed');ids.push(page);}
// Keep native autogenerated Board/PCB metadata untouched: only schematic pages are edited.
for(let i=0;i<6;i++){if(!(await eda.dmt_Schematic.modifySchematicPageName(ids[i],names[i])))throw Error('Page rename failed');}
return {project:p,schematicUuid:id,pages:ids.map((uuid,index)=>({uuid,index,name:names[index]})),info:await eda.dmt_Schematic.getSchematicInfo(id)};
