from pathlib import Path
import json
P=Path(__file__).parent
s=(P/'independent_audit.py').read_text();start=s.index('arraychecks=[]');end=s.index("assert all(a['actualCoordinatePatternPASS']")
s=s[:start]+'''from pattern_audit import verify_template
arraychecks=[]
for t in N['templates']:
 ok=verify_template(t,pos,old)
 arraychecks.append({'name':t['name'],'kind':t['kind'],'refs':t['refs'],'actualCoordinatePatternPASS':bool(ok),'meaning':'Exact baseline retention, not an array'if t['kind']=='PIN_FORCED_BASELINE'else 'Actual coordinate constraints checked'})
'''+s[end:]
(P/'independent_audit.py').write_text(s,encoding='utf8')
for name in['COMPLETE_B22_RECEIPT.md','write_receipt.py','REQUIREMENT_ACCEPTANCE_MATRIX.json']:
 path=P/name;s=path.read_text(encoding='utf8')
 s=s.replace('PASS_POSITIONAL_CENTRAL_MIRROR_ONLY','PARTIAL_CENTRAL_PAIRING_AXIS_MIRROR_HOLD')
 s=s.replace('5 of10 added real-net local checks','5 of12 added real-net pin-pair checks across10 IC/passive combinations')
 s=s.replace('All10added comparisons','All12added pin-pair comparisons across10 IC/passive combinations')
 s=s.replace('All10added comparisons are','All12added pin-pair comparisons across10 IC/passive combinations are')
 s=s.replace('VCM/VEX HF/FB/ISO centers use central positional mirror around U3; copper layers/pin identity are not mirrored.','VCM/VEX HF/FB/ISO centers use central positional pairing around U3; the requested common-axis reflection is NOT implemented and remains PARTIAL/HOLD. Copper layers/pin identity are not mirrored.')
 s=s.replace('HF/FB/ISO centers centrally paired about U3; this is not a footprint/net reflection','HF/FB/ISO centers centrally paired about U3; requested common-axis reflection is not implemented (HOLD); not a footprint/net reflection')
 s=s.replace('5failures cannot be hidden behind the inherited94PASS.','5failures cannot be hidden behind the inherited94PASS.12pairs are generated by10selected IC/passive combinations because each U11/U12 VDD cap matches two IC pads.')
 path.write_text(s,encoding='utf8')
print('Single review correction pass: explicit actual pattern audit, common-axis HOLD and12pair denominator; coordinates/figure unchanged')

